#[cfg(feature = "fcnet-ext")]
pub mod fcnet;
#[cfg(feature = "link-local-ext")]
pub mod link_local;
#[cfg(feature = "metrics-ext")]
pub mod metrics;
#[cfg(feature = "serial-console-ext")]
pub mod serial_console;
#[cfg(feature = "vsock-http-ext")]
pub mod vsock_http;
